language: python

python:
  - "2.7"
  - "3.4"

services:
  - postgresql
  - redis

# command to install requirements
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install -r requirements-dev.txt --use-mirrors

before_script:
  - psql template1 -c 'CREATE EXTENSION hstore;'

# command to run tests, e.g. python setup.py test
script:
  - "py.test --ds=chms_control.testsettings ./*/tests.py --cov=chms_control"
  - "flake8 ."
